#check path on your system + this line should work on Window
run:
	docker run -it -v D:\PC\GitHub\Test1\Test2:/app --rm -e DISPLAY=host.docker.internal:0 -v /tmp/.X11-unix:/tmp/.X11-unix brodzilla/py_currency_exchanger

stop:
	docker stop brodzilla/py_currency_exchanger